import bcrypt from "bcryptjs";
import jwt from "jsonwebtoken";
import User from "../../models/user/User.js";
import UserProfile from "../../models/user/UserProfile.js";
import UserLoyalty from "../../models/user/UserLoyalty.js";
import ApiError from "../../utils/ApiError.js";
import { OAuth2Client } from "google-auth-library";

const client = new OAuth2Client(process.env.GOOGLE_CLIENT_ID);

/**
 * Generate JWT token
 */
const generateToken = (userId, email) => {
  return jwt.sign(
    { id: userId, email },
    process.env.JWT_SECRET || "your-secret-key",
    { expiresIn: process.env.JWT_EXPIRATION || "7d" },
  );
};

/**
 * Generate refresh token
 */
const generateRefreshToken = (userId) => {
  return jwt.sign(
    { id: userId },
    process.env.JWT_REFRESH_SECRET || "your-refresh-secret",
    { expiresIn: "30d" },
  );
};

/**
 * Normalize user response for frontend
 */
const buildAuthUser = (user, profile = null, loyalty = null) => ({
  _id: user._id,
  id: user._id, // Keep backward compatibility
  user_id: user.user_id,
  customerId: user.user_id,
  email: user.email,
  fullName: profile?.full_name || null,
  phone: user.phone ?? null,
  provider: user.provider || "local",
  role: user.role,
  avatar: profile?.avatar || "",
  profile,
  loyalty,
});

const ensureUserRecords = async (user, profileData = null) => {
  const [profile, loyalty] = await Promise.all([
    UserProfile.findOne({ user_id: user.user_id }).lean(),
    UserLoyalty.findOne({ user_id: user.user_id }).lean(),
  ]);

  const tasks = [];
  if (!profile && profileData) {
    tasks.push(
      UserProfile.create({
        user_id: user.user_id,
        ...profileData,
      }),
    );
  }
  if (!loyalty) {
    tasks.push(
      UserLoyalty.create({
        user_id: user.user_id,
        total_points: 0,
      }),
    );
  }
  if (tasks.length > 0) {
    await Promise.all(tasks);
  }

  const nextProfile =
    profile || (profileData ? await UserProfile.findOne({ user_id: user.user_id }).lean() : null);
  const nextLoyalty =
    loyalty || (await UserLoyalty.findOne({ user_id: user.user_id }).lean());

  return { profile: nextProfile, loyalty: nextLoyalty };
};

/**
 * Register new user
 */
const register = async (userData) => {
  // ⚠️ SECURITY: Remove role from userData to prevent privilege escalation
  // Client should NEVER be able to set role during registration
  const {
    email,
    password,
    fullName,
    full_name,
    phoneNumber,
    phone,
    role: _ignoredRole,
    ...otherData
  } = userData;

  // Use phone if phoneNumber not provided (frontend sends 'phone')
  const userPhone = phoneNumber || phone;

  if (!userPhone) {
    throw new ApiError(400, "Phone number is required");
  }

  const profileData = {
    full_name: fullName || full_name,
    avatar: userData.avatar || "",
  };

  if (!profileData.full_name) {
    throw new ApiError(400, "Full name is required");
  }

  // Check if user already exists (only by email)
  const existingUser = await User.findOne({ email });

  if (existingUser) {
    throw new ApiError(400, "Email already registered");
  }

  // Create user - customerId and password will be auto-generated by User model pre-save hook
  // ✅ SECURITY: Force role to "customer" - never accept from client
  const user = await User.create({
    email,
    password_hash: password, // Don't hash here - User model will hash it
    phone: userPhone, // Changed from phoneNumber to phone to match User model
    role: "customer", // ✅ ALWAYS customer for public registration
    status: "active",
  });

  const { profile, loyalty } = await ensureUserRecords(user, profileData);

  // Generate tokens
  const token = generateToken(user._id, user.email);
  const refreshToken = generateRefreshToken(user._id);

  return {
    user: buildAuthUser(user, profile, loyalty),
    token,
    refreshToken,
  };
};

/**
 * Login user
 */
const login = async (phone, password) => {
  // Find user by phone number
  const user = await User.findOne({ phone }).select("+password_hash");

  if (!user) {
    throw new ApiError(401, "Số điện thoại hoặc mật khẩu không đúng");
  }

  if (user.status !== "active") {
    throw new ApiError(403, "Tài khoản chưa được kích hoạt");
  }

  // Check password
  const isPasswordValid = await bcrypt.compare(password, user.password_hash);

  if (!isPasswordValid) {
    throw new ApiError(401, "Số điện thoại hoặc mật khẩu không đúng");
  }

  user.last_login_at = new Date();
  await user.save();

  const { profile, loyalty } = await ensureUserRecords(user);

  // Generate tokens
  const token = generateToken(user._id, user.email);
  const refreshToken = generateRefreshToken(user._id);

  return {
    user: buildAuthUser(user, profile, loyalty),
    token,
    refreshToken,
  };
};

/**
 * Google OAuth authentication
 */
const googleAuth = async (token) => {
  try {
    // Kiểm tra Google Client ID có được config chưa
    if (!process.env.GOOGLE_CLIENT_ID) {
      console.error("❌ GOOGLE_CLIENT_ID không được cấu hình trong .env");
      throw new ApiError(500, "Chưa cấu hình Google OAuth trên server");
    }

    const audience = (process.env.GOOGLE_CLIENT_ID || "")
      .split(",")
      .map((id) => id.trim())
      .filter(Boolean);

    console.log("🔑 Verifying Google token with Client ID:", audience[0]);

    // Verify Google token
    const ticket = await client.verifyIdToken({
      idToken: token,
      audience: audience.length ? audience : process.env.GOOGLE_CLIENT_ID,
    });

    const payload = ticket.getPayload();
    const { email, name, picture, sub, email_verified } = payload || {};

    console.log("✅ Google token verified for:", email);

    if (!email) {
      throw new ApiError(401, "Tài khoản Google không có email");
    }

    if (email_verified === false) {
      throw new ApiError(401, "Email Google chưa được xác thực");
    }

    // Check if user exists
    let user = await User.findOne({
      $or: [{ google_id: sub }, { email }],
    });

    if (!user) {
      console.log("👤 Tạo user mới từ Google:", email);
      // Create new user - customerId will be auto-generated by User model
      user = await User.create({
        email,
        password_hash: await bcrypt.hash(Math.random().toString(36), 10), // Random password
        provider: "google",
        google_id: sub || null,
        role: "customer",
        status: "active",
        phone: null,
      });
    } else {
      console.log("👤 User đã tồn tại:", email);
      let shouldSave = false;

      if (sub && !user.google_id) {
        user.google_id = sub;
        shouldSave = true;
      }

      if (!user.provider) {
        user.provider = user.phone ? "local" : "google";
        shouldSave = true;
      }

      if (shouldSave) {
        await user.save();
      }
    }

    if (user.status !== "active") {
      throw new ApiError(403, "Tài khoản chưa được kích hoạt");
    }

    const { profile, loyalty } = await ensureUserRecords(user, {
      full_name: name,
      avatar: picture || "",
    });

    user.last_login_at = new Date();
    await user.save();

    // Generate tokens
    const jwtToken = generateToken(user._id, user.email);
    const refreshToken = generateRefreshToken(user._id);

    return {
      user: buildAuthUser(user, profile, loyalty),
      token: jwtToken,
      refreshToken,
    };
  } catch (error) {
    // Log chi tiết lỗi để debug
    console.error("❌ Google authentication error:", error.message);
    console.error("Error details:", error);

    // Nếu là ApiError đã tạo sẵn, throw nguyên bản
    if (error.statusCode) {
      throw error;
    }

    // Nếu là lỗi khác, throw với message chi tiết hơn
    throw new ApiError(
      401,
      `Đăng nhập Google thất bại: ${error.message || "Lỗi không xác định"}`,
    );
  }
};

/**
 * Refresh access token
 */
const refreshToken = async (refreshToken) => {
  try {
    const decoded = jwt.verify(
      refreshToken,
      process.env.JWT_REFRESH_SECRET || "your-refresh-secret",
    );

    const user = await User.findById(decoded.id);

    if (!user || user.status !== "active") {
      throw new ApiError(401, "Invalid refresh token");
    }

    const newToken = generateToken(user._id, user.email);

    return { token: newToken };
  } catch (error) {
    throw new ApiError(401, "Invalid or expired refresh token");
  }
};

/**
 * Forgot password
 */
const forgotPassword = async (email) => {
  const user = await User.findOne({ email });

  if (!user) {
    throw new ApiError(404, "User not found");
  }

  // Generate reset token (implement email sending)
  const resetToken = jwt.sign(
    { id: user._id },
    process.env.JWT_SECRET || "your-secret-key",
    { expiresIn: "1h" },
  );

  // TODO: Send reset email
  console.log("Reset token:", resetToken);

  return { message: "Password reset email sent" };
};

/**
 * Reset password
 */
const resetPassword = async (token, newPassword) => {
  try {
    const decoded = jwt.verify(
      token,
      process.env.JWT_SECRET || "your-secret-key",
    );

    const user = await User.findById(decoded.id);

    if (!user) {
      throw new ApiError(404, "User not found");
    }

    // Hash new password
    user.password_hash = newPassword;
    await user.save();

    return { message: "Password reset successfully" };
  } catch (error) {
    throw new ApiError(400, "Invalid or expired reset token");
  }
};

export default {
  register,
  login,
  googleAuth,
  refreshToken,
  forgotPassword,
  resetPassword,
};
